version: '3.9'
services:
  react-app:
    build:
      context: .
      dockerfile: ./docker/react/Dockerfile
    volumes:
      - ./reactApp :/usr/src/app
    command: sh -c "cd react-sample &&yarn start"
    ports:
    - "3000:3000"
    stdin_open: true 